name: Feature request (lego)
description: Suggest an idea for this project.
body:
  - type: dropdown
    id: license
    attributes:
      label: Analyzer License
      description: AGPL is not allowed.
      multiple: true
      required: true
      options:
        - No License
        - MIT
        - Apache-2.0
        - BSD-3-Clause
        - ISC
        - MPL-2.0
        - EPL-2.0
        - GPL-2.0-only
        - GPL-3.0-only
  - type: checkboxes
    id: license-check
    attributes:
      label: Analyzer License Checks
      options:
        - label: The file must start with `LICENSE` (capitalized).
          required: true
        - label: 'The file(s) must contain the required information by the license, e.g.: author, year, etc.'
          required: true
  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > test
        > jdslqkd

        The detectors are not allowed because of the number of false positives.
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I've searched similar issues on GitHub and didn't find any.
          required: true

  - type: dropdown
    id: type
    attributes:
      label: How do you use lego?
      options:
        - Library
        - Binary
        - Docker image
        - Through Traefik
        - Through Caddy
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      placeholder: Description.
    validations:
      required: true
